#!/usr/bin/env python3
"""
Initializes Admin/Master_Log.md from Admin/Syllabus/Class_Schedule.csv.

Safe by default: refuses to overwrite an existing Master_Log.md unless --force is passed.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
from pathlib import Path


def _read_schedule(schedule_csv: Path):
    with schedule_csv.open("r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise SystemExit(f"Empty schedule: {schedule_csv}")
    return rows


def _default_paths(date_iso: str, class_number: str):
    n = int(class_number)
    return {
        "assignment_path": f"Admin/Syllabus/Assignments/{date_iso}_class{n:02d}.md",
        "prep_path": f"Lectures/Prep/Packets/{date_iso}_class{n:02d}_prep.md",
        "review_path": f"Lectures/Reviews/{date_iso}_class{n:02d}_review.md",
        "notes_path": f"Lectures/Transcripts/raw/{date_iso}_class{n:02d}_notes.md",
    }


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--force", action="store_true", help="Overwrite existing Master_Log.md")
    args = p.parse_args()

    repo = Path.cwd()
    schedule_csv = repo / "Admin/Syllabus/Class_Schedule.csv"
    out_md = repo / "Admin/Master_Log.md"

    if out_md.exists() and not args.force:
        raise SystemExit(f"Refusing to overwrite existing {out_md}. Use --force.")

    rows = _read_schedule(schedule_csv)

    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M")

    lines = []
    lines.append("# Master Log (Backbone)\n")
    lines.append(
        "This file is the single source of truth for what exists, what’s next, and what quality checks have passed.\n"
    )
    lines.append(
        "If you give a command like “next prep doc”, the agent should consult the **Class Pipeline** table below.\n"
    )
    lines.append("\n## Status Codes\n")
    lines.append("- `todo` = not started\n- `draft` = generated but not QC’d\n- `final` = QC passed\n- `skip` = intentionally skipped\n")
    lines.append("\n## Project / Analysis Log\n")
    lines.append("| ID | Item | Output | Status | Notes |\n")
    lines.append("|---|---|---|---|---|\n")
    lines.append(
        "| P-001 | Extract syllabus into schedule | `Admin/Syllabus/Class_Schedule.csv` | final | Generated by `Admin/Scripts/extract_syllabus.py` |\n"
    )
    lines.append(
        "| P-002 | Create templates + QC standards | `Admin/Templates/` | final | Prep/review templates and QC checklists |\n"
    )
    lines.append(
        "| P-003 | Create command interface | `Admin/Command_Interface.md` | final | Standard prompts + procedures |\n"
    )
    lines.append(
        "| P-004 | Index past exams | `Exams/Exam_Spec.md` | draft | Skeleton created; still needs exam content extraction |\n"
    )
    lines.append(
        "| P-005 | Index past outlines | `Admin/Mapping/Past_Outlines_Index.md` | draft | Skeleton created; still needs outline-prior extraction |\n"
    )
    lines.append("\n## Class Pipeline\n")

    header = [
        "Class#",
        "Date",
        "Title",
        "Assignment",
        "MPC",
        "Prep Doc",
        "Prep Status",
        "Review Doc",
        "Review Status",
        "Notes",
        "Outline Updated",
        "Pred Acc",
        "Time Prep",
        "Time Review",
        "Exam Signals",
        "Last Touched",
        "Next Action",
    ]
    lines.append("| " + " | ".join(header) + " |\n")
    lines.append("|" + "|".join(["---"] * len(header)) + "|\n")

    for r in rows:
        class_number = r["class_number"]
        date_iso = r["date"]
        title = r["title"]
        mpc = r.get("mpc_sections", "")
        paths = _default_paths(date_iso, class_number)
        lines.append(
            "| "
            + " | ".join(
                [
                    class_number,
                    date_iso,
                    title,
                    f"`{paths['assignment_path']}`",
                    mpc or "",
                    f"`{paths['prep_path']}`",
                    "todo",
                    f"`{paths['review_path']}`",
                    "todo",
                    f"`{paths['notes_path']}`",
                    "N",
                    "",
                    "",
                    "",
                    "",
                    now,
                    "Prep",
                ]
            )
            + " |\n"
        )

    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote: {out_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
